name: Deployment Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test:coverage

      - name: Run Linting
        run: npm run lint

      - name: Build Artifacts
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          if [ -d dist ]; then
            git checkout --orphan gh-pages
            git --work-tree dist add --all
            git --work-tree dist commit -m "GitHub Pages deployment"
            git push origin HEAD:gh-pages --force
          fi
